import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeStyle from '../styles/scss/Home.module.scss'
import Header from '../components/Home/Header'
export default function Home() {
  return (
    <div style = {{
      width: '100%',
      height: 'auto',
      padding: '0',
      margin: '0',
      border: 'none',
      position: 'relative',
      overflow: 'hidden'
    }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  )
}
